# Generated by Django 4.2 on 2024-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadFileImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="files/")),
                ("img", models.ImageField(upload_to="imgs/")),
                ("remark", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "img",
            },
        ),
    ]
