# Generated by Django 4.2 on 2024-05-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="library",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("book_name", models.CharField(max_length=100, verbose_name="书名")),
                ("book_author", models.CharField(max_length=100, verbose_name="作者")),
                ("book_price", models.FloatField(verbose_name="价格")),
            ],
        ),
    ]
