# Generated by Django 4.2 on 2024-05-10 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sers", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="library",
            options={"verbose_name": "图书"},
        ),
        migrations.AlterModelTable(
            name="library",
            table="图书馆",
        ),
    ]
