# Generated by Django 4.2 on 2024-05-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("module_app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user1",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="token"
            ),
        ),
    ]
