# Generated by Django 4.2 on 2024-05-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("module_app1", "0002_alter_user1_token"),
    ]

    operations = [
        migrations.DeleteModel(
            name="user1",
        ),
        migrations.AlterField(
            model_name="user",
            name="token",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="token"
            ),
        ),
    ]
