# Generated by Django 4.2 on 2024-05-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("module_app1", "0003_delete_user1_alter_user_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="permissions_bank",
            field=models.ImageField(
                blank=True,
                choices=[(1, "管理员"), (2, "普通用户"), (3, "老板")],
                default=3,
                null=True,
                upload_to="",
                verbose_name="角色",
            ),
        ),
    ]
