# Generated by Django 4.2 on 2024-05-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("module_app1", "0004_user_permissions_bank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="permissions_bank",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "管理员"), (2, "普通用户"), (3, "老板")],
                default=3,
                null=True,
                verbose_name="角色",
            ),
        ),
    ]
